---
title: "Dropbox_pricing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
```

```{r}
dropbox <- read_csv("Pricing Project - Dropbox (Responses) - Form Responses 1.csv") %>%
  #mutate(id = seq(1, nrow(dropbox),1)) %>%
  mutate(tool = ifelse(`Do you use Dropbox as your main cloud storage?` == 'Yes', "Dropbox", `What cloud storage product do you use mostly?`)) %>%
  mutate(tool = ifelse(tool == "I don't use any cloud storage product/ I only use whatever space my compute have.", "computer", tool)) %>%
  mutate(main_tool = ifelse(tool == "Dropbox" | tool == "computer",  tool, "Others")) %>% 
  mutate(paying = ifelse(`How much are you paying for your Dropbox services?` == "I am using a free account" | `Are you paying for the cloud storage you mentioned above?` == "No", "No", NA)) %>%
  mutate(paying = ifelse(tool == "computer", "No", paying)) %>%
  mutate(paying = ifelse(is.na(paying), "Yes", paying)) %>%
  mutate(share_usage = ifelse(main_tool == "Dropbox", `With whom do you share Dropbox files?`, `With whom do you share files?` )) %>%
  mutate(share_usage = ifelse(str_detect(share_usage, regex("all of the above", ignore_case = T)), "All of the above", share_usage)) %>%
  # mutate(task_usage = ifelse(main_tool == "Dropbox", `Do you use any task management tool? e.g. Trello, Wunderlist, Google Calendar, Airtable, Notion, etc.`, `Do you use any task management tool? e.g. Trello, Wunderlist, Google Calendar, Airtable, Notion, etc._1`))
```

```{r}
colnames(dropbox)
```


# market share
```{r}
dropbox%>%
  group_by(tool) %>%
  tally() %>% 
  mutate(market_share = percent(n/sum(n))) %>%
  arrange(desc(n)) %>%
  ggplot(aes(x = reorder(tool, n), y = n, group = tool, fill = tool)) + geom_text(aes(label = market_share), hjust = -0.2) + geom_col(alpha = 0.4) + coord_flip() +
  theme(legend.position = "none") +
  labs(x = "tools", y = "count", title = "Market Share") + 
  ylim(0, 30) 

```

```{r}

```

# proportion of paying for cloud storage
```{r}
dropbox %>% 
  #filter(!is.na(dropbox_paying)) %>%
  #mutate(dropbox_paying = ifelse(dropbox_paying == "I am using a free account", "No", "Yes")) %>%
  #group_by(dropbox_paying) %>%
  group_by(main_tool, paying) %>%
  tally() %>%
  filter(main_tool != "computer") %>%
  ggplot(aes(x = main_tool, y = n, fill = paying)) + geom_col(position = "fill", alpha = 0.8)
```

```{r}
dropbox %>% 
  #filter(!is.na(dropbox_paying)) %>%
  #mutate(dropbox_paying = ifelse(dropbox_paying == "I am using a free account", "No", "Yes")) %>%
  #group_by(dropbox_paying) %>%
  group_by(tool, paying) %>%
  tally() %>%
  filter(tool != "computer") %>%
  filter(!str_detect(tool, regex("baidu", ignore_case = T))) %>%
  ggplot(aes(x = tool, y = n, fill = paying)) + geom_col(position = "fill", alpha = 0.6) +
  labs(y = "Percentage of customers", title ="Percentage of customers paying for clould storage service")
```

```{r}
# dropbox %>%
#   group_by(main_to  ol, share_usage) %>%
#   tally() %>%
#   filter(main_tool != "computer") %>%
#   #filter(!str_detect(tool, regex("baidu", ignore_case = T))) %>%
#   ggplot(aes(x = main_tool, y = n, fill = share_usage)) + geom_col(position = "fill", alpha = 0.6)
  
  
```


```{r}
dropbox %>%
  filter(`Would you be willing to pay extra money for Dropbox's task management features?` !="No" ) %>%
  select(`How much are you paying for your Dropbox services?`, `Would you be willing to pay extra money for Dropbox's task management features?`, `By how much are you willing to pay for Dropbox's task management features (in addition to what you are paying for its storage services)?`)
```
```{r}
demand <- dropbox %>%
  filter(main_tool == "Dropbox") %>%
  rename(wtp = `By how much are you willing to pay for Dropbox's task management features (in addition to what you are paying for its storage services)?`) %>%
  select(wtp) %>%
  mutate(wtp = parse_number(wtp)) %>%
  group_by(wtp) %>%
  tally() %>%
  arrange(desc(wtp)) %>%
  mutate(qty_demand = cumsum(n)) %>%
  mutate(extra_profit = wtp * qty_demand) #%>%
  # select(-n) %>%
  # gather(type, number, -wtp)

p1 <- demand %>%
  ggplot(aes(x = wtp, y = qty_demand)) + geom_point() +  
  geom_smooth(color = 'light blue', size = 1) +
  theme(legend.position = "none") +
  labs( x = "price", y = "Quantity Demanded", title = "Demand Curve" , subtitle = "for existing Dropbox customers")

p2 <- demand %>%
  ggplot(aes(x = wtp, y = extra_profit)) + geom_point() +  
  geom_smooth(color = 'pink', size = 1) +
  theme(legend.position = "none") +
  labs( x = "price", y = "Extra Profit", title = "Extra Revenue" , subtitle = "for existing Dropbox customers")

gridExtra::grid.arrange(p1,p2,nrow = 1)
```

```{r}
500000000/27 * 25
```

```{r height = 1080p, width = 1080p}
dropbox %>%
  filter(!is.na(`If Dropbox develops features for task management (e.g. To do list, calendar), are you willing to switch to Dropbox?`)) %>%
  group_by(`If Dropbox develops features for task management (e.g. To do list, calendar), are you willing to switch to Dropbox?`) %>%
  tally() %>%
  mutate(nr_customer = n + 21/2) %>%
  rename(willing_to_switch_task = `If Dropbox develops features for task management (e.g. To do list, calendar), are you willing to switch to Dropbox?`) %>%
  filter(willing_to_switch_task != "Maybe") %>%
  mutate(perc = nr_customer/sum(nr_customer)) %>%
  ggplot(aes(x = willing_to_switch_task, y = perc, fill = willing_to_switch_task)) + geom_col() + 
  labs(y = "Ratio", 
       x = "If you are willing to switch to Dropbox for task management features", 
       title = "Willing to switch to Dropbox for task management features") +
  theme(legend.position = "none") +
  geom_text(aes(label = round(perc, 2)), vjust = -0.2)
  

```

